name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build --build-arg FULLCHAIN="${{ secrets.CERTIFICATE }}" \
                       --build-arg PRIVKEY="${{ secrets.PRIVATE_KEY }}" \
                       -t technoed-hack-frontend:latest .
        
      - name: Stop existing container
        run: |
          docker stop technoed-hack-frontend-nginx-1 || true
          docker rm technoed-hack-frontend-nginx-1 || true
        
      - name: Run Docker container
        run: |
          docker run -d --name technoed-hack-frontend-nginx-1 -p 80:80 -p 443:443 \
            technoed-hack-frontend:latest
